name: 'pr-reviewer-lottery-action'
description: 'Github action to randomly assign a recently opened PR to a reviewer from a given group'
author: 'clayton-duarte'
inputs:
  github_token:
    description: 'secrets.GITHUB_TOKEN'
    required: true
  whatever:
    description: 'whenever'
    default: 'default value if applicable'
    required: false
outputs:
  pushPayload:
    description: 'testing pushPayload'
runs:
  using: 'node12'
  main: 'dist/index.js'
