name: 'pr-reviewer-lottery-action'
description: 'Github action to randomly assign a recently opened PR to a reviewer from a given group'
author: 'clayton-duarte'
inputs:
  github_token:
    description: 'secrets.GITHUB_TOKEN'
    required: true

  possible_reviewers:
    description: 'List of Github logins separated by comma. E.g. "clayton-duarte,l0rdcafe"'
    required: false
    default: ''
outputs:
  pushPayload:
    description: 'testing pushPayload'
runs:
  using: 'node12'
  main: 'dist/index.js'
