name: Build & Test
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Compile
        run: yarn package

      - name: Test
        run: yarn test
          
  test-default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Runs default
        uses: ./
        with:
          # if no possible reviewers is passed, we assume that's all collaborators
          github_token: ${{ secrets.GITHUB_TOKEN }}

  test-with-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Runs with reviewers option
        uses: ./
        with:
          reviewers: 'clayton-duarte,l0rdcafe,ryansmit'
          github_token: ${{ secrets.GITHUB_TOKEN }}
