name: 'build-test'
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: Build and Test
        run: yarn all
          
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Runs Itself
        # ./ stands for the task in the root of this repo
        uses: ./
        with:
          # if no possible reviewers is passed, we assume that's all collaborators
          # reviewers: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
